unused macro
seunshare.c:53:9: error: macro is not used [-Werror,-Wunused-macros]
#define BUF_SIZE 1024
        ^

Signed-off-by: Christian Göttsche <cgzones@googlemail.com>